### ISSUE TITLE
Docker image errors with "no such file or directory"

### ISSUE THREAD

**Issue by jpds** [vale-cli/vale#128] opened 2019-05-27 13:17 UTC
If one runs the copy usage command on: https://hub.docker.com/r/jdkato/vale/

It simply errors with:

```
docker run --rm -v $(pwd)/styles:/styles \
              --rm -v $(pwd)/fixtures/styles/demo:/docs \
              -w /docs \
              jdkato/vale .
standard_init_linux.go:207: exec user process caused "no such file or directory"
```

Same with any other command:

```
docker run --rm -it jdkato/vale:latest /vale
standard_init_linux.go:207: exec user process caused "no such file or directory"
```

**Comment by jdkato** [comment] 2019-05-27 15:57
Do those paths exist?

The example command shows how to use local components, but it doesn't create them. In other words, you need to mount your own `styles` and `docs` directories.

**Comment by jpds** [comment] 2019-05-30 15:15
They do, but it's also erroring in the same way without them.

**Comment by jdkato** [comment] 2019-06-02 17:04
This should be fixed with the latest Docker release (`docker pull jdkato/vale:latest`).

**Comment by jdkato** [comment] 2019-06-11 18:08
I'll close this for now -- feel free to re-open if the issue isn't fixed for you, though.

**Closed as completed by jdkato** 2019-06-11 18:08 UTC
Labels: Status: Fixed, Type: Bug

**Comment by akosma** [comment] 2019-09-30 11:24
I'm building an image using the `Dockerfile` provided in this project. I then copy inside the 1.7.1 tool downloaded from the releases page. The resulting image always generates this error. Is there any hidden dependency in the tool? Whether I'm downloading it directly from the releases, building an image from `scratch`, building an image from "alpine", I always get the same error in this ticket. I do not get this error from other Go-based executables, using the same base image and parameters.

**Comment by akosma** [comment] 2019-09-30 11:52
I've managed to build a working image using this Dockerfile (targeting Asciidoctor files checked using Microsoft's rules) by downloading the latest release tar file, building it on the spot, and creating a new image.

```Dockerfile
############################
# STEP 1
############################
FROM golang:alpine AS builder

# Install build tools
RUN apk update && apk add --no-cache wget zip tar make
WORKDIR /

RUN wget https://github.com/errata-ai/vale/archive/v1.7.1.tar.gz
RUN tar -xvzf v1.7.1.tar.gz

WORKDIR /vale-1.7.1
RUN make

# Install syntax file
RUN wget https://github.com/errata-ai/Microsoft/releases/download/v0.6.1/Microsoft.zip
RUN unzip Microsoft.zip


############################
# STEP 2
############################
FROM alpine:latest

RUN apk add --update \
    python \
    py-pip \
    asciidoctor \
   && pip install docutils \
   && rm -rf /var/cache/apk/*

# Copy our static executable.
COPY --from=builder /vale-1.7.1/bin/vale /vale
COPY --from=builder /vale-1.7.1/Microsoft /styles/Microsoft
COPY vale.ini /.vale.ini

ENTRYPOINT ["/vale"]
```
