### ISSUE TITLE
Error highlighting effected by surrounding lines

### ISSUE THREAD

**Issue by rohennes** [vale-cli/vale#674] opened 2023-09-07 09:16 UTC
Hello, 

The highlighting of an incorrect term seems to be effected by adding line breaks, removing instances of the same error on a previous line etc. I am expecting only "using" to flag in the below example. 

This is simlar to #673 but not only limited to content in backticks. Thanks as always for your help and responsiveness!

https://regex101.com/r/8NYdwH/1    

```yml
---
extends: substitution
ignorecase: false
level: suggestion
link: https://redhat-documentation.github.io/vale-at-red-hat/docs/main/reference-guide/termssuggestions/
message: "Depending on the context, consider using '%s' rather than '%s'."
action:
  name: replace
swap:
  "(?<!by) using": " by using| that uses"

```

## Text

```markdown
Start by using this.

Start by using this.
Start using this.

Start by using this.

Start by using this.

Start using this.
```

**Comment by aireilly** [comment] 2023-09-27 16:31
Here is a complete test case: https://github.com/aireilly/vale-test/tree/test-case

This test case shows the error in Sublime vale-ls, CLI, VS Code.

**Comment by aireilly** [comment] 2023-09-27 20:57
I think this is related to how Asciidoctor builds the HTML. Here is one of our test fixtures. It gets rendered as a single paragraph.
![image](https://github.com/errata-ai/vale/assets/74046732/cd446986-34e0-48dd-b41f-5984ed6b1a62)

I played around with [hard-line-breaks](https://docs.asciidoctor.org/asciidoc/latest/blocks/hard-line-breaks/#per-document) in the vale.ini:

```
[asciidoctor]
hardbreaks-option = YES
```

But this didn't really make any difference.

**Comment by aireilly** [comment] 2023-10-03 10:52
Seeing this error frequently. Any file that contains multiple instances of the same error string can show errors on the wrong lines and miss actual errors.

**Comment by jdkato** [comment] 2023-10-03 21:56
> Here is a complete test case: https://github.com/aireilly/vale-test/tree/test-case
> 
> This test case shows the error in Sublime vale-ls, CLI, VS Code.

This is a different issue than what is being discussed here (see #691).

**Comment by jdkato** [comment] 2024-01-15 12:33
This OP's issue is a duplicate of #502.

**Closed as completed by jdkato** 2024-01-15 12:33 UTC
Labels: Type: Bug, duplicate
