### ISSUE TITLE
Vale should ignore quoted text in RST

### ISSUE THREAD

**Issue by thedrow** [vale-cli/vale#119] opened 2019-04-17 13:26 UTC
- OS (e.g., macOS, Windows, Linux, etc.): Linux
- Install method (e.g., Go, Homebrew, direct download, etc.): go get
- Vale version (the result of `vale -v`): vale version master

I have some text in a quote block:
```rst
  | I have a very large collection
```

I have added the following configuration:
```
SkippedScopes = script, style, pre, figure, blockquote
```

But vale still complains about the use of very.

**Comment by jdkato** [comment] 2019-04-17 20:27
It appears that the nested line block (`|`) is causing the issue:

```html
<blockquote>
  <div class="line-block">
    <div class="line">I have a very large collection</div>
  </div>
</blockquote>
```

**Comment by thedrow** [comment] 2019-04-18 12:49
No even if I remove the `|` the word "very" is not ignored.

**Comment by jdkato** [comment] 2019-04-18 16:04
It's hard to say with only one line of text, but I can't reproduce this. 

Here's an example test file:

```rst
I have a very large collection

    I have a very large collection

I have a very large collection
```
And `.vale.ini`:

```ini
MinAlertLevel = suggestion
SkippedScopes = script, style, pre, figure, blockquote

[*.rst]
BasedOnStyles = vale
```

Which results in (line 3 is ignored):

```console
 test.rst
 1:10  warning  Consider removing 'very'  vale.Editorializing 
 5:10  warning  Consider removing 'very'  vale.Editorializing 
```

(The aforementioned line block does indeed break this, though.)

**Comment by thedrow** [comment] 2019-04-21 09:50
Here's my full vale.ini:

```ini
StylesPath = styles
MinAlertLevel = warning

[*.rst]
# `errata` represents your custom house style (feel free to re-name it).
#
# You can add your own rules at `/styles/errata`.
BasedOnStyles = proselint, write-good, Joblint, errata

# Catch flag of repeated words (e.g., 'the the') as warnings.
#
# NOTE: We use 'warning' here because there are some edge cases that we don't
# want to be marked as errors (e.g., 'that that').
vale.Repetition = warning

SkippedScopes = script, style, pre, figure, blockquote
```

Here's the full text:

```rst
Martin Fowler defines a `Circuit Breaker`_ in the following fashion:

  | The basic idea behind the circuit breaker is very simple.
  | You wrap a protected function call in a circuit breaker object, which monitors
  | for failures.
  | Once the failures reach a certain threshold, the circuit breaker trips,
  | and all further calls to the circuit breaker return with an error,
  | without the protected call being made at all.
  | Usually you'll also want some kind of monitor alert if the circuit breaker
  | trips.

Each :ref:`health check <Health Checks>` has it's own Circuit Breaker.
Once a circuit breaker is tripped, the messages are stored
in the :ref:`messages backlog` until the health check recovers and the circuit
is once again closed.
```

**Comment by jdkato** [comment] 2019-04-21 21:09
`SkippedScopes` is a [core-level](https://errata-ai.github.io/vale/config/#available-options) attribute, so it should be defined above the syntax-specific sections (e.g., with `MinAlertLevel`).

**Comment by thedrow** [comment] 2019-04-22 07:35
Yes, that is correct.
There should be a warning if a key that does not belong in the section is present.

**Comment by jdkato** [comment] 2019-04-22 07:39
I'm going to keep this open until I have a chance to look into why line blocks can break `SkippedScopes`.

**Comment by thedrow** [comment] 2019-04-22 09:31
This is strange. When I run vale locally, the error no longer appears.
However it does appear in [CI when using errata.sh](https://travis-ci.com/celery/ceps/builds/109119665#L336).

**Comment by jdkato** [comment] 2019-04-22 17:01
By default, `errata.sh` installs Vale v1.0.4 and `SkippedScopes` was introduced in v1.3.0.

**Comment by thedrow** [comment] 2019-08-07 08:21
I installed the latest Vale version, 1.7.0 in CI and it's reporting errors in blockquotes.
See https://travis-ci.com/celery/ceps/builds/122232746#L382

**Comment by thedrow** [comment] 2019-08-07 08:47
It doesn't do so in your test case.
The difference probably comes from the fact that my blockqoutes are in a glossary section.

**Comment by jdkato** [comment] 2019-08-07 14:58
I still haven't looked into this, but I haven't forgotten. I'll definitely try to figure this out before I put out another release.

**Comment by jdkato** [comment] 2019-08-09 04:32
It appears that this issue is related to https://github.com/errata-ai/vale/issues/95#issuecomment-441308412 in the sense that I believe only the location is incorrect&mdash;in other words, the error is correct and exists outside of a blockquote, but the *location* is being incorrectly reported.

For example, in the case of `content/draft/celery-5-high-level-architecture.rst` in your CI output, the `proselint.Very` error is coming from the following sentence:

> In previous versions of Celery there are issues with the protocol which can
cause Celery to generate **very** large messages.

---

The cause of this seems to be that `rst2html` doesn't handle Sphinx directives well (such as `.. glossary::`):

- If I pass `--quiet` (which Vale currently does) the glossary section is removed entirely, which means that the content Vale lints (HTML) differs from the file that it looks up the locations in (reStructuredText). This is causing the locations to be incorrectly reported when an error that exists in the document also exists *earlier* in a blockquote.

- If I don't pass `--quiet`, `rst2html` produces in-text errors like the following:

    ```html
    <div class="system-message">
        <p class="system-message-title">System Message: ERROR/3 (<tt class="docutils">test.rst</tt>, line 4)</p>
        <p>Unknown directive type &quot;glossary&quot;.</p>
        <pre class="literal-block">
    .. glossary::
    
    Circuit Breaker
    Martin Fowler defines a `Circuit Breaker`_ in the following fashion:
    
      The basic idea behind the circuit breaker is TODO simple.
      You wrap a protected function call in a circuit breaker object, which monitors
      for failures.
      Once the failures reach a certain threshold, the circuit breaker trips,
      and all further calls to the circuit breaker return with an error,
      without the protected call being made at all.
      Usually you'll also want some kind of monitor alert if the circuit breaker
      trips.
    </pre>
    </div>
    ```
---

It appears that Pandoc handles this much better, but I'd rather not have it as a dependency. Does Sphinx have a command-line tool that can convert a single reStructuredText file to HTML?

(My understanding is that it only offers `sphinx-build`, but I'm not very familiar with the toolchain.)

**Comment by thedrow** [comment] 2019-08-10 14:22
`sphinx-build` accepts a list of filenames as an argument.
I'm not sure how well that approach will work as you'll have broken links in case a document references another document.

**Comment by jdkato** [comment] 2019-08-12 18:28
The issue with `.. glossary::` specifically should be fixed (the issue with Sphinx directives in general is still somewhat a WIP).

**Closed as completed by jdkato** 2019-08-12 18:28 UTC
Labels: Status: Fixed, Type: Bug, Type: Markup
