### ISSUE TITLE
Multiple scopes

### ISSUE THREAD

**Issue by ChrisChinchilla** [vale-cli/vale#74] opened 2018-08-07 09:47 UTC
Hey there @jdkato We've been working on some tooling using vale for our Test the docs project, I'll have a lot of feedback and maybe PRs soon, but one quick question.

is it possible to define multiple scopes? For example in [EndingPreposition](https://github.com/errata-ai/vale/blob/master/styles/demo/EndingPreposition.yml):

```
message: "Don't end a sentence with '%s'"
extends: existence
level: suggestion
scope: sentence
raw:
  - '\b(?:at|from|of|to|in|for|on|by)[.!]'
```

This detects prepositions at the end of a sentence, but not at the end of a paragraph. I guess I could create multiple rules, but that seems extraneous to me. 🤔

**Comment by jdkato** [comment] 2018-08-07 16:26
Hi,

No, this isn't currently possible. That said, it should also be unnecessary in most cases -- if you're needing to define more than one scope, you're probably better off not defining one (i.e., just using the default `text`).

With regards to your example above, I'm unable to reproduce the issue: since the end of a paragraph is also the end of sentence, I'm getting the expected results. For example, running Vale (with `EndingPreposition` enabled) on

> [ ... ]
>
> There's was nothing to be frightened of. This is another sentence.
>
> We're starting a new paragraph. A good test is hard to come by.
>
> Here's another one!

results in the following:

```shell
[...]
test.md:30:38:demo.EndingPreposition:Don't end a sentence with 'of.'
test.md:32:61:demo.EndingPreposition:Don't end a sentence with 'by.'
```
(The full test can [be found here](https://github.com/errata-ai/vale/blob/master/fixtures/styles/demo/test.md).)

Do you have an example where Vale is failing?

**Comment by ChrisChinchilla** [comment] 2018-08-08 12:06
@jdkato Huh, you're right. I actually think I'm finding some issues with the VSC plugin for Vale, as if I test using the CLI, or Atom, everything works as expected. We've also found some other issues with the VSC plugin, I'll investigate there further. 🤔

**Comment by jdkato** [comment] 2018-08-08 21:01
I'll close this for now, but feel free to let me know if there's anything more I can do.

**Closed as completed by jdkato** 2018-08-08 21:01 UTC
Labels: Status: Resolved, Type: Question
