### ISSUE TITLE
Word presence in accept.txt interferes with existence rule

### ISSUE THREAD

**Issue by timothymcmackin** [vale-cli/vale#744] opened 2023-12-27 19:48 UTC
### Check for existing issues

- [X] Completed

### Environment

macos, homebrew, 2.30.0

### Describe the bug / provide steps to reproduce it

I want to catch instances of a specific two-word phrase, regardless of capitalization. I wrote this rule:

```
extends: existence
message: "Do not use the phrase 'something interesting'"
level: error
tokens:
   - 'something Interesting'
   - 'something interesting'
```

I also added the word `Interesting` to my list of correctly spelled words in accept.txt because the word should be capitalized in my use case.

I ran Vale on this file:

```
Hello! This is a test file.

It doesn't do something interesting.

Really, it's not interesting.

But maybe it could do something Interesting.
```

Vale catches the uncapitalized "something interesting" but not the capitalized "something Interesting." I've tried setting `ignorecase` to true and using a regex like `something [Ii]nteresting` but it still doesn't catch both instances.

Minimal reproduction:
https://github.com/timothymcmackin/vale-capitalization-bug

**Comment by jdkato** [comment] 2024-01-15 12:47
This is technically working as intended: by adding `Interesting` to a vocabulary, you've marked it as an exception that applies to all rules (not just `spelling`-based ones).

If you want to maintain a list of words that only apply to `spelling` rules, you should use a custom dictionary or an [ignore file](https://vale.sh/docs/topics/styles/#ignoring-non-dictionary-words).

Additionally, as of the latest release, you can bypass vocabulary exceptions on a per-rule basis by adding `vocab: false`.

**Closed as completed by jdkato** 2024-01-15 12:47 UTC
Labels: Status: Resolved, Type: Bug
