### ISSUE TITLE
Hyphenated words in exceptions list still being flagged as errors

### ISSUE THREAD

**Issue by JamesDuff2021** [vale-cli/vale#647] opened 2023-06-14 12:35 UTC
### Check for existing issues

- [X] Completed

### Environment

OS: Windows
Install method: choco
Vale version: 2.24.4

### Describe the bug / provide steps to reproduce it

We've been working on a Vale rule that enforces sentence style capitalization. We have included a few exceptions for some proper nouns that we use. Everything seems to be working well, except for some terms with hyphens. Here is the rule:
extends: capitalization
message: "'%s' should use sentence-style capitalization."
level: warning
match: $sentence
threshold: 0.9
exceptions:

Package Builder
High-Def Render Pipeline
H-Def Render Pipeline
High Definition Render Pipeline
Vale allows all exceptions except for: High-Def Render Pipeline. I've tried a bunch of other terms with hyphens and as long as the first part of the word is more than 1 character, it doesn't work as an exception. Do you have any idea why this one exception is not working or any suggestions to get it working?

**Comment by lantrix** [comment] 2023-07-03 10:46
I have the same issue.

**Comment by f-hollow** [comment] 2023-07-07 08:37
I also have a similar hyphenation issue. It might be caused by #199.

My environment:

| OS | macOS Catalina 10.15.4 |
| --- | --- |
| Install method | Direct download |
| Vale version | 2.24.2 |


My `Vocab/Terms/accept.txt`:

```
ABCDEF
ABC-DEF
```

Result:

- `ABCDEf` - flagged as `Use ABCDEF instead of ABCDEf`
- `ABC-DEf` - not flagged, escaping `\-` has no effect either


I hope there is a way to add hyphenated words to vocabularies!

**Comment by jdkato** [comment] 2023-07-24 20:40
Both issues mentioned here should be fixed now.

**Closed as completed by jdkato** 2023-07-24 20:40 UTC
Labels: Status: Fixed, Type: Bug
