### ISSUE TITLE
v2.10.0: CI installation not working due to name change

### ISSUE THREAD

**Issue by acalvo** [vale-cli/vale#337] opened 2021-03-11 10:24 UTC
Hi! The installation method described in https://docs.errata.ai/vale/install#using-vale-with-a-continuous-integration-ci-service doesn't work with v2.10.0.

The reasons seems to be the name of the files. Up to v2.9.1 they were for example `vale_2.9.1_Linux_64-bit.tar.gz`, now it's `vale_2.10.0_Linux_amd64.tar.gz`.

**Comment by th0ger** [comment] 2021-03-11 13:27
Similar issue here. Our Docker builds fails due to exit code 60 from the `sh -s v.X.Y.Z` step. No error message is given, and vale is not installed (or upgraded).
```
$ curl -sfL https://install.goreleaser.com/github.com/ValeLint/vale.sh | sh -s v2.9.0
ValeLint/vale info checking GitHub for tag 'v2.9.0'
ValeLint/vale info found version: 2.9.0 for v2.9.0/Linux/64-bit
$ echo $?
60
$ vale --v
vale version 2.8.0
```

**Comment by th0ger** [comment] 2021-03-11 14:57
By the way, also older releases are broken. It' seem like the gorelaser script is broken in general.
```
$ curl -sfL https://install.goreleaser.com/github.com/ValeLint/vale.sh | sh -s v2.8.1
ValeLint/vale info checking GitHub for tag 'v2.8.1'
ValeLint/vale info found version: 2.8.1 for v2.8.1/Linux/64-bit
$ echo $?
60

**Comment by jdkato** [comment] 2021-03-11 15:05
This should be fixed now.

**Closed as completed by jdkato** 2021-03-11 15:05 UTC
Labels: Status: Fixed, Type: Bug

**Comment by th0ger** [comment] 2021-03-11 15:08
@jdkato I'just tested it (with commands as above) but it still fails with error code 60. Is this two different issues?

**Comment by jdkato** [comment] 2021-03-12 02:35
I can't reproduce your issue @th0ger, is it still not working?

**Comment by th0ger** [comment] 2021-03-12 06:48
@jdkato I found it to be another issue, caused by firewall. The failing part was:
```
$ curl -w '%{http_code}' -L https://github.com/ValeLint/vale/releases/download/v2.10.0/vale_2.10.0_Linux_64-bit.tar.gz
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
It would have been nice if this error message had been thrown (it's suppressed by `-s`)... but again, that code was autogenerated by godownloader... which appears to be no longer maintained...

Anyway, thanks for maintaining Vale :-)
