### ISSUE TITLE
Detection issue with phrases in a vocabulary's accept.txt

### ISSUE THREAD

**Issue by carolstran** [vale-cli/vale#753] opened 2024-01-12 15:02 UTC
### Check for existing issues

- [X] Completed

### Environment

- OS: **macOS**
- Install method: **Homebrew**
- Vale version: **3.0.3** (but also tested on 2.30.0)

### Describe the bug / provide steps to reproduce it

While using vocabularies, I noticed the CLI produces non-deterministic results with phrases listed in the `accept.txt` and especially when the phrase includes other words present in the file.

Example use case - `accept.txt`:

```txt 
emnify
emnify IoT SuperNetwork
```

Text on the page:

```md
# EMnify IoT SuperNetwork

Cellular is the most used wireless network technology...
```

The old branding spelled the company name as `EMnify` but now it's all lowercase, so we need to check for that. Additionally, we define `emnify IoT SuperNetwork` so that the capitalization is accurate and consistent across our docs. But when running vale on the above scenario, it doesn't always catch the error. 

<details><summary>Terminal screenshot - v3.0.3</summary>
<img width="769" alt="Screenshot 2024-01-12 at 14 21 59" src="https://github.com/errata-ai/vale/assets/26869552/65a389fa-8172-4741-8015-cf16d0028fb6">
</details> 

Another use case - `accept.txt`

```
emnify
emnify Portal
```

When the two words are together, the P in portal should be capitalized - but there are other instances where we write "portal" independently and it should be capitalized.

The following screenshots include both the text with the error (`emnify portal`) and the terminal output (no errors).

<details><summary>v3.0.3</summary>
<img width="965" alt="Screenshot 2024-01-12 at 14 40 46" src="https://github.com/errata-ai/vale/assets/26869552/1deffc58-712d-44c6-9216-2e35511bd282">
</details> 

<details><summary>v2.30.0</summary>
<img width="943" alt="Screenshot 2024-01-12 at 14 44 03" src="https://github.com/errata-ai/vale/assets/26869552/1b285a90-4834-4d79-8361-f06c560b5af7">
</details> 

Should I be using regex instead? The [docs](https://vale.sh/docs/topics/vocab/#overview) say that phrases are possible, but any additional guidance is apprecaited 🙏🏼 

This issue seems to be similar to https://github.com/errata-ai/vale/issues/744, except that there are no rules involved. However, if you'd prefer I close this issue and comment on that one to reduce the backlog, please let me know!

**Comment by jdkato** [comment] 2024-01-15 12:54
The non-deterministic results issue should be resolved in the latest release. 

However, I was unable to reproduce your issue exactly: it's unclear to me why one case is no results at all (it should have been either 'use emnify' or 'use emnify IoT SuperNetwork').

Can you confirmed that this is fixed in v3.0.4?

**Closed as completed** 2024-01-21 11:26 UTC
Labels: Status: Fixed, Type: Bug
