### ISSUE TITLE
Style exceptions not behaving as expected

### ISSUE THREAD

**Issue by StarfallProjects** [vale-cli/vale#154] opened 2019-10-18 11:02 UTC
- OS: Windows 10
- Install method: chocolatey
- Vale version: 1.7.1

Hi! We're seeing some unexpected results with title case rules and exceptions.

Our setup is:
```
StylesPath = styles
MinAlertLevel = warning
[*.{md}]
BasedOnStyles = EventStore, 18F, write-good
18F.Titles = No
```
Then in `styles/EventStore/Titles.yml`
```
---
extends: capitalization
message: "'%s' should be in sentence case"
level: warning
scope: heading
match: $sentence
exceptions:
  - Event Store
```

Vale then does the following:

`## Event Store` -> ok
`## Creating a connection to Event Store` -> warning

There is a further quirk. If I modify the exceptions as follows:

```
exceptions:
  - Event Store
  - Creating a connection to Event Store
```

It gives the same results:

`## Event Store` -> ok
`## Creating a connection to Event Store` -> warning

What should the behaviour be?

**Comment by jdkato** [comment] 2019-10-18 17:00
`Event` and `Store` should be added as individual exceptions:

```yaml
---
extends: capitalization
message: "'%s' should be in sentence case"
level: warning
scope: heading
match: $sentence
exceptions:
  - Event 
  - Store
```
This should allow both `## Event Store` and `## Creating a connection to Event Store` to pass. I'll make this more clear in the documentation.

**Comment by StarfallProjects** [comment] 2019-10-19 07:13
Thanks for clarifying! Is there no way to do it for specific phrases? We still want it to flag "Create a new Event and add it to the Store", for example

**Comment by jdkato** [comment] 2019-10-19 08:33
No, not currently.

The problem is that this quickly becomes a computationally intensive task (relative to the overall run time, anyway). For example, your 10-word example would have 55 possible exceptions by itself (the `n=1, ..., n=10` n-grams).

And, on the other hand, the drawbacks of the more naive algorithm don't seem to be that practical: Your example assumes that you would encounter a title that is randomly capitalized (i.e., not following a standard capitalization style) with words perfectly matching exceptions.

Have you found that the current implementation is generating false negatives in your actual content?

**Comment by StarfallProjects** [comment] 2019-10-21 14:51
We're trying to use Vale to support people learning our style guide, who aren't tech writers themselves - so being able to really precisely control what we flag would be useful. My examples were from a current draft page. But if it's not possible then no worries. I think we might resolve this by erring on the side of flagging too much - so let it issue a warning on "Creating a connection to Event Store" (which I'm sure people will quickly learn to ignore), rather than potentially missing things.

Thanks for discussing this, and clarifying Vale's behaviour.

**Comment by jdkato** [comment] 2019-10-22 18:26
I'll leave this open until I get a chance to revisit changing the way this works.

**Comment by jdkato** [comment] 2020-02-26 02:00
This should be available in the next release. I'll close the issue once the docs are updated and the release is available.

**Closed as completed** 2020-03-07 19:25 UTC
Labels: Status: Resolved, Type: Docs, Type: Enhancement, Type: Question
