### ISSUE TITLE
Configuration not loaded on Ubuntu 18.04

### ISSUE THREAD

**Issue by jpoesen** [vale-cli/vale#81] opened 2018-09-22 10:28 UTC
Hi, this tool looks great! 

Just trying to get it to run, but not getting anywhere: no matter how I configure vale, I always get the same output:

```
✔ 0 errors, 0 warnings and 0 suggestions in 1 file.
```

Installed on Ubuntu 18.04 via snap as per the getting started instructions.
One should be able to use the styles 'vale', 'proselint', and 'write-good' without specifying a StylePath nor downloading/installing anything else, correct?

I've simplified the .vale file as much as possible, and put it inside the same directory as my markdown file:
```
# Global settings (applied to every syntax)
[*]

# List of styles to load
BasedOnStyles = vale
```
the output of running ```vale myfile.md``` is always:
```
✔ 0 errors, 0 warnings and 0 suggestions in 1 file.
```

The file contains a lot of text content, and I even introduced grammar errors, spelling errors, etc. I've tried with various markdown files, tried using proselint, and so on... whatever I do, I always get the same output.

Is there any way to debug what is going on? It feels like whatever I put in the .vale file is always ignored...

Thanks.

**Comment by jpoesen** [comment] 2018-09-22 16:50
Update: I got vale to work as expected by uninstalling the snap version and downloading the latest binary release (v1.0.3).

I don't know what causes the version installed with snap to fail silently. 
If anyone has a clue I'd be happy to help test on Ubuntu.

**Comment by jdkato** [comment] 2018-09-22 17:00
> One should be able to use the styles 'vale', 'proselint', and 'write-good' without specifying a StylePath nor downloading/installing anything else, correct?

This is correct (assuming you're using at least v1.0.0). That said, I can confirm that the snap version is indeed failing on Ubuntu 18.04:

```
$ ls -a
.  ..  test.md  .vale
$ cat test.md
this this is a test.
$ cat .vale
[*]
BasedOnStyles = vale
$ snap install --edge vale
vale (edge) v1.0.3 from Joseph Kato (jdkato) installed
$ which vale
/snap/bin/vale
$ vale test.md
✔ 0 errors, 0 warnings and 0 suggestions in 1 file.
```

**Comment by jdkato** [comment] 2018-09-22 20:59
So, this appears to be related to the [`confinement`](https://docs.snapcraft.io/reference/confinement) setting: 

> [strict] The snap has read and/or write rights only in its own install space and selected areas. It has access to libraries it bundles and/or provided by the core or ubuntu-core snap.

It should work if you install with the following command:

```shell
$ snap install --edge --classic vale
```
If you can verify that this does work for you, I'll update the documentation.

(I also should probably include the various package manager builds in the CI suite, too ...)

**Comment by jdkato** [comment] 2018-09-25 02:09
In my testing, passing `--classic` does appear to resolve the issue. So, I've updated the documentation and I'm going to mark this as resolved.

If you're still having trouble, feel free to comment further.

**Comment by jdkato** [comment] 2018-09-25 19:27
I definitely closed this prematurely: passing the `--classic` flag allows Vale to function correctly with Markdown, *but not with AsciiDoc or reStructuredText*.

It appears the issue is that Vale depends on external binaries (`asciidoctor` and `rst2html`), which aren't visible to the snapped version. It's unclear to me how (or if) this can be resolved without defeating the purpose of providing a snap altogether: *making installation easier*. FWIW, Hugo (which depends on the same two binaries) seems to [have the same issue](https://discourse.gohugo.io/t/solved-asciidoctor-asciidoc-not-found-in-path/10017).

At this point, I'm inclined to just drop official support for Snapcraft.

**Closed as completed** 2018-09-27 16:14 UTC
Labels: Status: Won't Fix, Type: Bug, Platform: Linux
