### ISSUE TITLE
Feature: Allow Vale to ignore output by class

### ISSUE THREAD

**Issue by infotexture** [vale-cli/vale#201] opened 2020-05-02 20:33 UTC
## Vale ignores elements

As of v2.0, Vale can check DITA content and ignores the contents of `<codeblock>`, `<tt>`, and `<codeph>` elements by default.

IIRC, this is implemented by converting DITA content to HTML using the standard HTML5 transformation provided by [DITA Open Toolkit](https://www.dita-ot.org), and ignoring the HTML elements to which the aforementioned DITA elements are converted, including `<code>`, `<pre>`, and `<tt>`.

A variety of other DITA elements with literal content (such as `<msgph>`, `<systemoutput>`, `<userinput>`, or `<varname>` from the software domain) can be ignored by adding additional HTML elements such as `<kbd>`, `<samp>`, and `<var>` to the `IgnoredScopes` list in `.vale.ini`. 

See dita-ot/docs@fff2e66 for example:

```ini
# Inline-level HTML tags to ignore
# By default, `code` and `tt` are ignored.
IgnoredScopes = code, kbd, samp, tt, var
```

## DITA-OT converts DITA elements to HTML elements and classes

However, there are various inline and block-level DITA elements (such as `<apiname>`, `<cmdname>`, `<example>`, `<filepath>`, `<msgnum>` or `<parmname>`) for which no HTML element equivalent exists. 

DITA-OT generates these as HTML `<span>` or `<div>` elements with corresponding CSS classes.

## Allow Vale to ignore classes

To allow these and other elements to be ignored, it would be helpful if the Vale configuration could be extended with an additional option that defines CSS classes to be ignored in HTML output, for example:

```ini
# HTML classes to ignore
IgnoredClasses = apiname, cmdname, example, filepath, msgnum, parmname
```

This feature would also help to support DITA [specialization](http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/archSpec/base/specialization.html#specialize), and enable DITA-specific [Markup-based configuration](https://errata-ai.gitbook.io/vale/getting-started/markup#markup-based-configuration), as the DITA [`@outputclass`](http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/langRef/attributes/commonAttributes.html#common-atts) attribute could be used to flag any other content that Vale should ignore.

**Comment by jdkato** [comment] 2020-05-02 21:05
This is actually already implemented and used "under the hood," so to speak. So, in the next release, I'll just expose this as a setting (probably `IgnoredClasses`, as suggested).

**Comment by infotexture** [comment] 2020-05-02 21:26
Brilliant, you rock! 💯 

We're working on linting the DITA-OT docs with Vale in https://github.com/dita-ot/docs/pull/284, and this would save us a lot of extra `vocab.txt` entries for toolkit-specific parameters.

**Comment by jdkato** [comment] 2020-05-07 20:30
This should be ready to go in [`v2.2.0`](https://github.com/errata-ai/vale/releases/tag/v2.2.0). Let me know if you run into any issues.

**Comment by infotexture** [comment] 2020-05-12 21:05
@jdkato Thanks for the quick implementation. 🙏 

Could it be that the current implementation only checks for **exact** matches of the ignored classes?

I added the sample ignore string to my config as suggested above:

```ini
# HTML classes to ignore
IgnoredClasses = apiname, cmdname, example, filepath, msgnum, parmname
```

and tested v2.2.0 with the [dita-command-arguments.dita](https://github.com/dita-ot/docs/blob/develop/parameters/dita-command-arguments.dita) file from the DITA-OT docs, assuming this would exclude `<parmname>` elements such as on [Line 332](https://github.com/dita-ot/docs/blob/develop/parameters/dita-command-arguments.dita#L332):

```xml
<parmname>--logfile</parmname>=<varname>file</varname>
```

— but I got the exact same number of errors & warnings as without the `IgnoredClasses` option.

When generating HTML output, DITA-OT adds additional classes to each element to reflect the class hierarchy of specialized elements. Since elements like `<parmname>` and `<varname>` are specialized from `<keyword>`, both classes are included in the output as follows:

```html
<span class="keyword parmname">--logfile</span>=<var class="keyword varname">file</var>
```

On a hunch, I modified the `IgnoredClasses` option to include the `keyword` class AND the `parmname` class as a single string — which significantly reduced the number of errors:

```ini
IgnoredClasses = keyword parmname
```

Would it be feasible to implement partial matching for the ignored classes within the class attribute values, so that it would be sufficient to add a single class like `parmname` to the `IgnoredClasses` option without having to specify the full class hierarchy like `keyword parmname`?

This would probably be useful not only for DITA, but for other HTML-based output as well, as many CSS frameworks may apply multiple classes at once, and the exact order or combinations in which they appear may not be known in advance.

**Comment by jdkato** [comment] 2020-05-15 18:37
Partial matching is indeed the intended behavior. I'll look into resolving this in the next release.

**Closed as completed** 2020-05-19 19:36 UTC
Labels: Status: Resolved, Type: Enhancement

**Comment by jdkato** [comment] 2020-05-21 18:43
This should be working as expected now.

**Comment by infotexture** [comment] 2020-05-23 19:58
🙏 Thanks, indeed it is. 🎉
